image: mobiledevops/flutter-sdk-image

pipelines:
  branches:
    master:
      - step:
          max-time: 120
          size: 2x
          script:
            - ls
#            - export ANDROID_SDK_ROOT=/opt/android-sdk
#            - export ANDROID_HOME=/opt/android-sdk
            - flutter --version
            - flutter upgrade
            - flutter pub get
            - flutter analyze
            - flutter build apk
          trigger: automatic
          artifacts:
            - "build/app/outputs/apk/release/app-release.apk"